sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tBzcY7y9iR2o5cQRZpa
    access-key-secret: p4J2RV53m0OOZCjFWfdzTG1iQ0usYq
    bucket-name: sky-wangwu
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wxca45010d35d67872
    secret: b175d44b373c1b42c71e0163e8eb0461